---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: demo-alpha
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-app
  name: my-app
  namespace: demo-alpha
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app
    spec:
      containers:
      - command:
        - /bin/tail
        - -f
        - /dev/null
        image: busybox
        name: busybox
        resources: {}
status: {}
